name: faro_dart
description: Grafana Faro but for dart
version: 0.0.3
homepage: https://github.com/cedricziel/faro_dart
repository: https://github.com/cedricziel/faro_dart

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^0.13.5
  synchronized: ^3.1.0
  uuid:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  shelf: ^1.4.1
  shelf_test_handler: ^2.0.2
