name: faro_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/cedricziel/faro_dart
repository: https://github.com/cedricziel/faro_dart

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.1.0
  synchronized: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
